object V {
  val cassandraDriverVersion     = "4.14.1"
  val scala213Version            = "2.13.8"
  val scala212Version            = "2.12.16"
  val scala3Version              = "3.1.3"
  val supportedScalaVersions     = List(scala213Version, scala212Version, scala3Version)
  val zioVersion                 = "1.0.15"
  val zio2Version                = "2.0.0"
  val zioJsonVersion             = "0.3.0-RC10"
  val zioPreludeVersion          = "1.0.0-RC15"
  val zioMagicVersion            = "0.3.10"
  val zioKafkaVersion            = "0.17.1"
  val zio2KafkaVersion           = "2.0.0"
  val zioHttpVersion             = "2.0.0-RC9"
  val testcontainersScalaVersion = "0.40.10"
  val mysqlConnnectorJVersion    = "8.0.29"
  val postgresqlDriverVersion    = "42.3.3"
  val slf4jVersion               = "1.7.32"
  val logbackVersion             = "1.2.6"
  val flywayVersion              = "8.1.0"
  val cassandraMigrationsVersion = "2.5.0_v4"
  val liquibaseVersion           = "4.13.0"
  val nettyVersion               = "4.1.79.Final"
}
